./oneclassSVM.py ./input-15 oneclassSVM 10
./oneclassSVM.py ./input-15 oneclassSVM 9
./oneclassSVM.py ./input-15 oneclassSVM 8
./oneclassSVM.py ./input-15 oneclassSVM 7
./oneclassSVM.py ./input-15 oneclassSVM 6
./oneclassSVM.py ./input-15 oneclassSVM 5
./oneclassSVM.py ./input-15 oneclassSVM 4
./oneclassSVM.py ./input-15 oneclassSVM 3
./oneclassSVM.py ./input-15 oneclassSVM 2
./oneclassSVM.py ./input-15 oneclassSVM 1
