./weightedRandomforest.py ./input-15 weightedRandomforest 10
./weightedRandomforest.py ./input-15 weightedRandomforest 9
./weightedRandomforest.py ./input-15 weightedRandomforest 8
./weightedRandomforest.py ./input-15 weightedRandomforest 7
./weightedRandomforest.py ./input-15 weightedRandomforest 6
./weightedRandomforest.py ./input-15 weightedRandomforest 5
./weightedRandomforest.py ./input-15 weightedRandomforest 4
./weightedRandomforest.py ./input-15 weightedRandomforest 3
./weightedRandomforest.py ./input-15 weightedRandomforest 2
./weightedRandomforest.py ./input-15 weightedRandomforest 1
