./weightedSVM.py ./input-15 weightedSVM 10
./weightedSVM.py ./input-15 weightedSVM 9
./weightedSVM.py ./input-15 weightedSVM 8
./weightedSVM.py ./input-15 weightedSVM 7
./weightedSVM.py ./input-15 weightedSVM 6
./weightedSVM.py ./input-15 weightedSVM 5
./weightedSVM.py ./input-15 weightedSVM 4
./weightedSVM.py ./input-15 weightedSVM 3
./weightedSVM.py ./input-15 weightedSVM 2
./weightedSVM.py ./input-15 weightedSVM 1
